# Generated by Django 5.1.2 on 2024-10-19 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('sex', models.CharField(max_length=10)),
                ('family_id', models.CharField(max_length=50)),
                ('head_of_household', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_number', models.CharField(max_length=100)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('sub_category', models.CharField(choices=[('Art', 'Art'), ('English', 'English'), ('Arabic', 'Arabic')], max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.individual')),
            ],
        ),
    ]
